// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgg5OUo8VCp5DGcCnSU37tRTmCWeES5aA',
    appId: '1:739281803160:web:af8a34285acf5cf324fded',
    messagingSenderId: '739281803160',
    projectId: 'memorystation-d823b',
    authDomain: 'memorystation-d823b.firebaseapp.com',
    storageBucket: 'memorystation-d823b.firebasestorage.app',
    measurementId: 'G-MNL4X982CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQEp8W8e2k2PSqHbH5tl7IFgwR7A9JAY',
    appId: '1:739281803160:android:ce9c24bdbfd3428224fded',
    messagingSenderId: '739281803160',
    projectId: 'memorystation-d823b',
    storageBucket: 'memorystation-d823b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkhAvfL19-D1Wz_NgYOe6DkLFUOFJZvHw',
    appId: '1:739281803160:ios:5e32297608e23c2024fded',
    messagingSenderId: '739281803160',
    projectId: 'memorystation-d823b',
    storageBucket: 'memorystation-d823b.firebasestorage.app',
    iosBundleId: 'com.example.memoryStation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkhAvfL19-D1Wz_NgYOe6DkLFUOFJZvHw',
    appId: '1:739281803160:ios:5e32297608e23c2024fded',
    messagingSenderId: '739281803160',
    projectId: 'memorystation-d823b',
    storageBucket: 'memorystation-d823b.firebasestorage.app',
    iosBundleId: 'com.example.memoryStation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgg5OUo8VCp5DGcCnSU37tRTmCWeES5aA',
    appId: '1:739281803160:web:6880a0f23131406224fded',
    messagingSenderId: '739281803160',
    projectId: 'memorystation-d823b',
    authDomain: 'memorystation-d823b.firebaseapp.com',
    storageBucket: 'memorystation-d823b.firebasestorage.app',
    measurementId: 'G-Q5NLCCBSSF',
  );
}
